apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticities.caus.rss.uni-stuttgart.de
spec:
  group: caus.rss.uni-stuttgart.de
  names:
    kind: Elasticity
    listKind: ElasticityList
    plural: elasticities
  scope: Namespaced
  version: v1


